# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CircleciConfigMerge < Formula
  desc "Generate .circleci/config.yml by merging multiple files"
  homepage "https://github.com/suzuki-shunsuke/circleci-config-merge"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/download/v1.1.0/circleci-config-merge_1.1.0_darwin_amd64.tar.gz"
      sha256 "42a3828d9337ccd68049d7033c74bfb2665a577cb29c6dd9a9e468de64897e00"

      def install
        bin.install "circleci-config-merge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/download/v1.1.0/circleci-config-merge_1.1.0_linux_amd64.tar.gz"
      sha256 "f591df8f8c92e25432974250e687a1ce484a319d68ee73979c25a96f227ab403"

      def install
        bin.install "circleci-config-merge"
      end
    end
  end

  test do
    system "#{bin}/circleci-config-merge --version"
  end
end
