# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CircleciConfigMerge < Formula
  desc "Generate .circleci/config.yml by merging multiple files"
  homepage "https://github.com/suzuki-shunsuke/circleci-config-merge"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/download/v1.0.1/circleci-config-merge_1.0.1_darwin_amd64.tar.gz"
      sha256 "d284b3095ff735883d4d1609f1bed5f96956390a3781224977de76c14c799c8d"

      def install
        bin.install "circleci-config-merge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/circleci-config-merge/releases/download/v1.0.1/circleci-config-merge_1.0.1_linux_amd64.tar.gz"
      sha256 "53849b7ac263977e487e284aea014acd2cb7e1f87ebc1888501dbea99d67deba"

      def install
        bin.install "circleci-config-merge"
      end
    end
  end

  test do
    system "#{bin}/circleci-config-merge --version"
  end
end
